### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/badger2040#1]
### Phase 1 - Make this stuff work

* [x] - port the Badger W `badger_os.py` back to regular Badger
* [x] - port the Badger W `badger2040w.py` to `badger2040.py`
* [ ] - figure out if much we can de-duplicate the above (not super urgent)
* [ ] - ensure all Badger W examples fail gracefully on Badger, they should be mostly compatible *except* stuff like Clock where Badger 2040 has a USER button (and the example has manual time set) vs Badger 2040 W which tries to get time via NTP.
* [x] - ensure lib/ stuff is baked into firmware and badger_os/examples stuff is appended as a littlefs filesystem
* [ ] - target an explicit release of pimoroni-pico
* [x] - add workflow to lint Python examples
* [ ] - add .zip distribution of examples for copying to non `-with-badger-os` releases?

### Phase 2 - Update docs & references

* [x] - Update badger2040 and badger2040w shop pages to link to firmware releases here
* [x] - Update learning portal examples to do the same
* [ ] - Update learning portal examples to new Badger 2040 API (which will match 2040 W mostly)
* [ ] - Update docs in pimoroni-pico to mark the Badger 2040 builds there as deprecated and point here
* [ ] - Add porting guide doc covering any major differences between old Badger 2040 and new setup

### Phase 3 - Delete all the things!

* [x] - Remove badger2040 .yml files from GitHub actions on pimoroni-pico
* [x] - Remove badger2040 docs & examples from pimoroni-pico

**Comment by Gadgetoid** [comment]
PRs to migrate over:

* https://github.com/pimoroni/pimoroni-pico/pull/339
* https://github.com/pimoroni/pimoroni-pico/pull/479 - should we have a converter to make raw framebuffer .bin files for *all* PicoGraphics pen types? Could be handy
* https://github.com/pimoroni/pimoroni-pico/pull/341 - wait for response, possibly port this myself
* https://github.com/pimoroni/pimoroni-pico/pull/314 - wait for response, possibly port this myself
* https://github.com/pimoroni/pimoroni-pico/pull/310 - this would be really cool to have in the standard example set somehow
